### ISSUE TITLE
frappeui.com is showing the storybook

### ISSUE THREAD

**Issue by penieldev** [frappe/frappe-ui#96]
frappeui.com is just showing the storybook instead of the actual website. It was working fine a few hours ago.

![image](https://github.com/frappe/frappe-ui/assets/46922290/930db5c4-7f63-44dc-ac8b-b40c0c42d19f)

**Comment by penieldev** [comment]
I'm not sure, but maybe it's because of this in `netlify.toml` ?

```toml
[build]
  publish = "storybook-static"
  command = "yarn build-storybook"
```
